name: Sectors
version: '${version}'
main: me.jm3l.sectors.Sectors
author: jm3L
api-version: 1.20
commands:
  sectors:
    description: Use Sectors.
    aliases: [s, sectors, sec]
permissions:
  sec.admin:
    default: op
