name: Sectors
version: '${version}'
main: me.jm3l.sectors.Sectors
author: jm3L
api-version: 1.20
depend: [ ProtocolLib ]
commands:
  sectors:
    description: Use Sectors.
    aliases: [s, sectors, sec, S, Sectors, Sec]
  savesectors:
    description: Save sectors.yml
permissions:
  sec.admin:
    default: op
